### ISSUE TITLE
Separated daemon and gui builds

### ISSUE THREAD

**Issue by msva** [Librevault/librevault#47]
Hi there!
What do you think about patching `CMakeLists.txt` to separate build for **daemon** (with some simple cli, maybe), *skipping Qt GUI*, and **Qt GUI** *without daemon*?
First one can be pretty useful when installing `librevault` on servers (vps/vds/dedicated) in case of using them as seedbox or NAS.
Second - for "thin" clients.

For now, as I can see, `CMakeLists.txt` unconditionally checks for Qt5 things and unconditionally build both GUI and daemon.

// Althought, ideally, "simple cli" should be buildable without daemon too. In analogy with, for example, `transmission`.

**Comment by skobkin** [comment]
+1 for this.
It would be cool if we could build librevault withour QT or X server.

**Comment by xen0l** [comment]
I would appreciate this as well

**Comment by msva** [comment]
I've patched buildsystem for this (see mentioned pull-request).
Although, it is still gui settings needs to be patched, for example, by adding form in settings dialog to allow user to specify default remote address (which gui will use at every start), and also change error message (in case of inability to start local daemon) to dialog with the same fields (host and port of remote instance) and checkbox to save that permanently.

**Comment by GamePad64** [comment]
Fixed in 21ab97f72f3bc68343abe55c3ba2a3a22c97abb2. Daemon builds do not require Qt5, and daemon and GUI can be built separately.

**Comment by msva** [comment]
@GamePad64 Thanks, but, actually, it is not fully fixed. It is still ".desktop" file and librevault.svg installs in daemon-only build
// btw, that was fixed in my PR (#58), which I closed after your commited alsmost same changes (but I initially missed that you've not fixed .desktop and .svg installation) ;)

**Comment by GamePad64** [comment]
Oh, my mistake, fixed ;)
